title: GlueTube

baseurl: "/~emersonjsc" # the subpath of your site, e.g. /blog
metadata: "/home/emersonjsc/gluetube/_data"

exclude:
  - Gemfile
  - Gemfile.lock
  - update.sh
  - makefile

# Build settings
theme: minima

# Recomendo esta leitura para entender o gerador de paginas individuais
# https://github.com/avillafiorita/jekyll-datapage_gen
page_gen-dirs: false
page_gen:

# Uma pagina para cada peca para mostrar informações
  - data: 'studio'
    template: 'piece' # Na pasta _layout
    name: 'id'
    title: 'title'
    dir: 'pieces'

# Uma pagina para cada peca para tocar a peca
  - data: 'studio'
    template: 'cinema' # Na pasta _layout
    name: 'id'
    title: 'title'
    dir: 'cinemas'

# Uma pagina para cada autor
  - data: 'studio'
    template: 'author' # Na pasta _layout
    name: 'author'
    title: 'author'
    dir: 'authors'

# Uma pagina para cada categoria
  - data: 'studio'
    template: 'category' # Na pasta _layout
    name: 'category'
    title: 'category'
    dir: 'categories'
