title: GlueTube

baseurl: "/~marilellis/gluetube" # the subpath of your site, e.g. /blog

exclude:
  - Gemfile
  - Gemfile.lock
  - update.sh
  - makefile

# Build settings
theme: minima

#collections:
#  scores:
#      output: true
#      permalink: '/:collection/:path/'

page_gen-dirs: true

page_gen:
  - data: 'studio'
    template: 'studio_gallery'
    name: 'title'
    dir: 'studio'
    
  - data: 'authors'
    template: 'gallery_authors'
    name: 'author_name'
    dir: 'authors'
    
  - data: 'categories'
    template: 'gallery_categories'
    name: 'category_title'
    dir: 'categories'
